const images = {
  SplashImage: () => require('../../src/assets/splash/splash-image.png'),
  KhmerFlag: () => require('../../src/assets/images/kh-flag.png'),
  HomeIcon: () => require('../../src/assets/images/home-icon.png'),
  OrderRequest: () => require('../../src/assets/images/list-icon.png'),
  OrderIcon: () => require('../../src/assets/images/order-icon.png'),
  ProfileIcon: () => require('../../src/assets/images/profile-icon.png'),
  AppLogo: () => require('../../src/assets/images/app-logo.png'),
  BellIcon: () => require('../../src/assets/images/bell-icon.png'),
  LocationIcon: () => require('../../src/assets/images/location.png'),
  WalletIcon: () => require('../../src/assets/images/wallet.png'),
  EditIcon: () => require('../../src/assets/images/pencil-icon.png'),
  MessageIcon: () => require('../../src/assets/images/message-icon.png'),
  DirectionIcon: () => require('../../src/assets/images/direction-icon.png'),
  SwipeRightIcon: () => require('../../src/assets/images/swipe-right-icon.png'),
  SuccessDollar: () => require('../../src/assets/images/success-dollar.png'),
  DarkLightIcon: () => require('../../src/assets/images/dark-light.png'),
  LanguageIcon: () => require('../../src/assets/images/language.png'),
  EditIcon: () => require('../../src/assets/images/edit-icon.png'),
  ChangePasswordIcon: () => require('../../src/assets/images/change-pass.png'),
  ContactUsIcon: () => require('../../src/assets/images/contact.png'),
  AboutUsIcon: () => require('../../src/assets/images/aboutus.png'),
  SignOutIcon: () => require('../../src/assets/images/sign-out.png'),
  DeleteIcon: () => require('../../src/assets/images/delete.png'),
  EyeIcon: () => require('../../src/assets/images/eye-icon.png'),
  HelpCenterCover: () => require('../../src/assets/images/help-center.png'),
  GlobalIcon: () => require('../../src/assets/images/global.png'),
  FacebookIcon: () => require('../../src/assets/images/fb.png'),
  EmailIcon: () => require('../../src/assets/images/email.png'),
  TelegramIcon: () => require('../../src/assets/images/telegram.png'),
  MainCallIcon: () => require('../../src/assets/images/main-call.png'),
  OrderPlaceIcon: () => require('../../src/assets/images/order-place.png'),
  AcceptIcon: () => require('../../src/assets/images/accept.png'),
  PickUpIcon: () => require('../../src/assets/images/pickup.png'),
  WashingIcon: () => require('../../src/assets/images/washing.png'),
  DeliverIcon: () => require('../../src/assets/images/delivery.png'),
  DeliverMoneyIcon: () => require('../../src/assets/images/deliver-money.png'),
  ReturnItemIcon: () => require('../../src/assets/images/return-item.png'),
  DashLine: () => require('../../src/assets/images/dash-line.png'),

  // static images
  MaleStaticImage: () => require('../../src/assets/images/male-static.png'),
  FemaleStaticImage: () => require('../../src/assets/images/female-static.png'),
  StaticHotel1: () => require('../../src/assets/static/hotel1-static.png'),
  StaticHotel2: () => require('../../src/assets/static/hotel2-static.png'),
  StaticHotel3: () => require('../../src/assets/static/hotel3-static.png'),
  StaticHoodie: () => require('../../src/assets/static/static-hoodie.png'),
  StaticDress: () => require('../../src/assets/static/static-dress.png'),
  StaticTShirt: () => require('../../src/assets/static/static-tshirt.png'),
  StaticCoat: () => require('../../src/assets/static/static-coat.png'),
  Metress: () => require('../../src/assets/static/metress.png'),
  Curtain: () => require('../../src/assets/static/curtain.png'),
  Tower: () => require('../../src/assets/static/tower.png'),
  Bartrobe: () => require('../../src/assets/static/bartrobe.png'),
  AddPersonOne: () => require('../../src/assets/static/addPerson-one.png'),
  AddPersonTwo: () => require('../../src/assets/static/addPerson-two.png'),
  AddPersonThree: () => require('../../src/assets/static/addPerson-three.png'),

  // sample: () => require('../../src/assets/'),
};

export default images;
